import { Unit } from '@/types';

export const units: Unit[] = [
  {
    id: 'introduction',
    title: '🇫🇷 Introduction',
    label: 'Basics & Greetings',
    description: 'Basic greetings, numbers, alphabet, and classroom vocabulary',
    topics: [
      { name: 'Greetings (Formal & Informal)', headings: ['salutations', 'greetings', 'bonjour', 'formal', 'informal'] },
      { name: 'Numbers 0-20', headings: ['nombres', 'numbers', '0-20', 'chiffres'] },
      { name: 'French Alphabet', headings: ['alphabet', 'pronunciation', 'prononciation'] },
      { name: 'Classroom Rules & Vocabulary', headings: ['salle de classe', 'classroom', 'règles'] },
      { name: 'Days of the Week', headings: ['jours', 'days', 'semaine'] },
      { name: 'Basic Conversation Phrases', headings: ['conversation', 'phrases', 'dialogues'] },
      { name: 'French Culture & Geography', headings: ['culture', 'géographie', 'geography', 'france'] },
      { name: 'Titles (Monsieur, Madame)', headings: ['monsieur', 'madame', 'mademoiselle', 'titles'] },
      { name: 'School Supplies Vocabulary', headings: ['fournitures', 'supplies', 'scolaires'] },
    ],
  },
  {
    id: 'unit-2',
    title: '🇫🇷 Unit 2',
    label: 'Activities & -ER Verbs',
    description: 'Activities, food, verb conjugation, and adverbs',
    topics: [
      { name: 'Olympic Sports Vocabulary', headings: ['sports', 'olympiques', 'olympic'] },
      { name: 'Activities (J\'aime/Je n\'aime pas)', headings: ['activités', 'activities', 'hobbies', 'aimer'] },
      { name: 'Food Vocabulary', headings: ['nourriture', 'food', 'manger', 'aliments'] },
      { name: 'Days of the Week', headings: ['jours', 'days', 'semaine'] },
      { name: 'Subject Pronouns (je, tu, il/elle, nous, vous, ils/elles)', headings: ['pronouns', 'pronoms', 'je, tu', 'subject'] },
      { name: 'Tu vs. Vous', headings: ['tu', 'vous', 'formal', 'informal', 'tutoiement'] },
      { name: '-ER Verb Conjugation', headings: ['conjugaison', 'conjugation', '-er verb', 'parler'] },
      { name: 'Common Verbs (parler, chanter, danser, manger, jouer)', headings: ['-er verbs', 'verbes en -er', 'parler', 'manger', 'jouer'] },
      { name: 'Adverbs (un peu, bien, beaucoup)', headings: ['adverbes', 'adverbs', 'un peu', 'bien', 'beaucoup'] },
      { name: 'Gender of Nouns (le, la, les)', headings: ['genre', 'gender', 'masculin', 'féminin'] },
      { name: 'Definite Articles', headings: ['articles définis', 'definite articles', 'le, la, les'] },
      { name: 'Preferences (préférer)', headings: ['préférer', 'preferer', 'likes', 'dislikes', 'adorer'] },
      { name: 'Negation (ne...pas)', headings: ['négation', 'negation', 'ne...pas', 'ne pas'] },
      { name: 'Nationalities', headings: ['nationalités', 'nationalities', 'pays', 'countries'] },
      { name: 'Classroom Expressions', headings: ['expressions', 'classroom', 'salle de classe'] },
    ],
  },
  {
    id: 'unit-3',
    title: '🇫🇷 Unit 3',
    label: 'Être, Avoir & Numbers',
    description: 'Classroom objects, numbers, prepositions, and key verbs',
    topics: [
      { name: 'Classroom Vocabulary (objects)', headings: ['salle de classe', 'classroom', 'objets', 'vocabulaire actif'] },
      { name: 'Numbers 20-100', headings: ['nombres', 'numbers', '20-100', 'vingt'] },
      { name: 'Prepositions (sous, sur, derrière)', headings: ['prépositions', 'prepositions', 'sous', 'sur', 'derrière'] },
      { name: 'Face & Body Parts Vocabulary', headings: ['visage', 'corps', 'body', 'face', 'parties du corps'] },
      { name: 'Indefinite Articles (un, une, des)', headings: ['articles indéfinis', 'indefinite articles', 'un, une, des'] },
      { name: 'Verb: Avoir (to have)', headings: ['avoir', 'to have'] },
      { name: 'Verb: Être (to be)', headings: ['être', 'etre', 'to be'] },
      { name: 'Negation Review', headings: ['négation', 'negation', 'ne...pas'] },
      { name: 'School Subjects', headings: ['matières', 'subjects', 'school subjects', 'scolaires'] },
      { name: 'Telling Time (Quelle heure est-il?)', headings: ['heure', 'time', 'quelle heure', 'telling time'] },
      { name: 'Christmas Vocabulary', headings: ['noël', 'noel', 'christmas', 'fête'] },
      { name: 'Questions with est-ce que', headings: ['est-ce que', 'questions', 'interrogative'] },
      { name: 'Combining Sentences (qui, quand, où)', headings: ['qui', 'quand', 'où', 'combining', 'relative'] },
      { name: 'Location Vocabulary (en ville, à la cantine, etc.)', headings: ['ville', 'location', 'où', 'cantine', 'endroits'] },
    ],
  },
  {
    id: 'unit-4',
    title: '🇫🇷 Unit 4',
    label: 'Aller, Futur Proche & Café',
    description: 'Unit 4 content',
    topics: [
      { name: 'Animals Vocabulary', headings: ['vocabulaire', 'actif', 'les', 'animaux'] },
      { name: 'Café Vocabulary & Ordering', headings: ['vocabulaire', 'actif', 'café'] },
      { name: 'Cinema Vocabulary', headings: ['vocabulaire', 'actif', 'cinéma'] },
      { name: 'Colors (rouge, bleu, vert)', headings: ['les', 'couleurs'] },
      { name: 'Expressions with Avoir (avoir faim/soif)', headings: ['j\'ai', 'faim', 'soif'] },
      { name: 'French Authors & Historical Figures', headings: ['warm', 'activities'] },
      { name: 'French Social Customs & Etiquette', headings: ['warm', 'activities'] },
      { name: 'Futur Proche (aller + infinitive)', headings: ['futur', 'proche', '(aller', 'infinitif)'] },
      { name: 'Interrogative Adjective Quel', headings: ['l\'adjectif', 'interrogatif', 'quel'] },
      { name: 'Numbers 60-1000', headings: ['les', 'nombres', '(60', '1000)'] },
      { name: 'Soccer/Football Vocabulary', headings: ['vocabulaire', 'actif', 'football'] },
      { name: 'Verb: Aller (to go)', headings: ['verbe', 'aller', '(to', 'go)'] },
      { name: 'Verb: Prendre (to take/order)', headings: ['verbe', 'prendre'] },
      { name: 'Verb: Voir (to see)', headings: ['verbe', 'voir'] },
    ],
  },
];
