/**
 * Centralized configuration for pipeline scripts.
 */

import { MODELS } from '@adaptive/shared/models';
export { MODELS };

import { DIFFICULTIES, type QuestionType } from '@adaptive/shared/enums';
export type { QuestionType };

import { loadUnitMaterials, extractTopicContent, type HeadingRef } from './learning-materials';

/** Minimal unit shape `computeTopicQuestionCap`/`estimateUnitQuestionCount` need to load a unit's
 * markdown and resolve one of its topics against it. */
interface UnitForQuestionCap {
  id: string;
  source_file_stem?: string | null;
  topics: Array<{ name: string; headings: HeadingRef[] }>;
}

/** Types generated by the structured (cheaper) model */
export const STRUCTURED_TYPES: QuestionType[] = ['multiple-choice', 'true-false'];
/** Types generated by the typed-answer (higher-quality) model */
export const TYPED_TYPES: QuestionType[] = ['fill-in-blank', 'writing'];

/** Returns the appropriate generation model for a given question type */
export function getModelForType(type: QuestionType): string {
  return STRUCTURED_TYPES.includes(type)
    ? MODELS.questionGenerationStructured
    : MODELS.questionGenerationTyped;
}

/** Estimated cost per Haiku 4.5 API call (~3k input + 1.5k output tokens) */
export const COST_PER_API_CALL = 0.008;

/** Chunk size for grouping questions into a single LLM call during the audit pass. Each question is
 * audited alone, because a question's audit verdict depends on which other questions share its call. */
export const AUDIT_GROUP_SIZE = 1;

/** Chunk size for grouping questions into a single LLM call during answer validation. Independent of
 * `AUDIT_GROUP_SIZE`, which governs only the audit pass. */
export const VALIDATION_GROUP_SIZE = 5;

/** Characters of extracted topic content that earn one question, when the per-topic/difficulty
 * question count isn't set explicitly via `--count`. */
export const CHARS_PER_QUESTION_CAP = 150;
/** Lower bound on the computed cap — even a very thin topic gets at least this many questions. */
export const MIN_QUESTIONS_PER_TOPIC_DIFFICULTY = 2;
/** Upper bound on the computed cap — a large topic doesn't grow the batch without limit. */
export const MAX_QUESTIONS_PER_TOPIC_DIFFICULTY = 10;

/**
 * The default question count for one topic at one difficulty, sized to how much material that
 * topic actually has. A 4-expression slang list and a multi-slide grammar topic shouldn't get the
 * same question budget. `--count` overrides this for the whole run.
 */
export function computeQuestionCap(charCount: number): number {
  const raw = Math.round(charCount / CHARS_PER_QUESTION_CAP);
  return Math.min(MAX_QUESTIONS_PER_TOPIC_DIFFICULTY, Math.max(MIN_QUESTIONS_PER_TOPIC_DIFFICULTY, raw));
}

/**
 * The question cap for one topic: loads the unit's markdown, extracts that topic's content, and
 * applies `computeQuestionCap`. The single place that sequence happens, so every caller that needs
 * a topic's cap (question generation itself, a pipeline step's dry-run estimate) reads the same
 * number for the same topic rather than each computing its own approximation.
 */
export function computeTopicQuestionCap(unitId: string, topic: string, units: UnitForQuestionCap[]): number {
  const materials = loadUnitMaterials(unitId, units);
  const content = extractTopicContent(materials, topic, units);
  return computeQuestionCap(content.length);
}

/**
 * A rough total question count for a unit: each topic's cap, once per difficulty. Not
 * authoritative — `questions-generate.ts --dry-run` computes and prints the exact per-pass numbers,
 * including the hybrid-mode split. This is for callers that only need a ballpark before deciding
 * whether to proceed (e.g. `pipeline-run.ts --dry-run`).
 */
export function estimateUnitQuestionCount(unitId: string, topics: string[], units: UnitForQuestionCap[]): number {
  return topics.reduce((sum, topic) => sum + computeTopicQuestionCap(unitId, topic, units) * DIFFICULTIES.length, 0);
}
