/**
 * Generates a zsh completion script from the same `CommandMeta[]` the dispatcher's help text is
 * built from, so completions never drift from the real flags. `pipeline completion zsh` runs this
 * fresh every time it's invoked (including on every new shell, via `source <(pipeline completion
 * zsh)` in `.zshrc`), so it always reflects the commands and PDFs on disk at that moment.
 */

import type { CommandMeta } from './types';

/** Escapes text going inside an `_arguments` spec's `[...]` message segment. */
function escapeBracketText(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/]/g, '\\]').replace(/:/g, '\\:');
}

/** Wraps a generated `_arguments` spec line in single quotes, escaping any embedded ones. */
function singleQuote(text: string): string {
  return `'${text.replace(/'/g, "'\\''")}'`;
}

function flagArgumentSpec(flagName: string, spec: NonNullable<CommandMeta['specs']>[string], unitsVarRef: string): string {
  const help = escapeBracketText(spec.help);
  const base = `--${flagName}[${help}]`;

  if (spec.type === 'boolean') return singleQuote(base);

  if (flagName === 'unit') return singleQuote(`${base}:unit:(${unitsVarRef})`);

  if (spec.choices && spec.choices.length > 0) {
    return singleQuote(`${base}:value:(${spec.choices.join(' ')})`);
  }

  return singleQuote(`${base}:value:`);
}

function commandArgumentsBlock(command: CommandMeta, unitsVarRef: string): string {
  if (!command.specs) {
    // A bespoke command with no defineCli() call — nothing to complete beyond --help.
    return "      _arguments '--help[Show this help]'";
  }
  // Deprecated aliases (e.g. --sync-db) aren't offered — completion advertises the canonical
  // flag name only.
  const lines = Object.entries(command.specs).map(
    ([flagName, spec]) => `        ${flagArgumentSpec(flagName, spec, unitsVarRef)} \\`,
  );
  return ['      _arguments \\', ...lines, "        '--help[Show this help]'"].join('\n');
}

export function generateZshCompletion(commands: CommandMeta[], opts: { units: string[] }): string {
  const commandDescribe = commands
    .map((c) => `    ${singleQuote(`${c.name}:${c.description.replace(/'/g, '')}`)}`)
    .join('\n');

  const commandCases = commands
    .map((c) => `    ${c.name})\n${commandArgumentsBlock(c, '$units')}\n      ;;`)
    .join('\n');

  const unitsArray = opts.units.map((u) => singleQuote(u)).join(' ');

  return `#compdef pipeline
# Generated by \`pipeline completion zsh\`. Commands and flags are read live from
# apps/pipeline/src/commands/*.ts; PDF-derived --unit values are read live from apps/pipeline/content/pdf. Re-run
# \`source <(pipeline completion zsh)\` (or open a new shell) after adding commands, flags, or PDFs.

_pipeline_commands() {
  local -a commands
  commands=(
${commandDescribe}
  )
  _describe 'command' commands
}

_pipeline() {
  local curcontext="$curcontext" state line
  local -a units
  units=(${unitsArray})

  _arguments -C \\
    '1: :_pipeline_commands' \\
    '*::arg:->args'

  case $words[1] in
    completion)
      _values 'shell' 'zsh' 'bash'
      ;;
${commandCases}
  esac
}

# #compdef only takes effect when this file is autoloaded from fpath, which the documented
# \`source <(pipeline completion zsh)\` install never does — that runs the whole file as a plain
# script body, where $funcstack[1] is not _pipeline, so this falls to compdef instead of trying to
# complete anything right now. Autoloaded (fpath) case: zsh invokes _pipeline directly as the
# completion widget, so $funcstack[1] is _pipeline and this calls it.
if [ "\${funcstack[1]}" = "_pipeline" ]; then
  _pipeline "$@"
else
  compdef _pipeline pipeline
fi
`;
}
