/**
 * Generates a bash completion script from the same `CommandMeta[]` the dispatcher's help text and
 * zsh completion are built from. Doesn't depend on the `bash-completion` package being installed
 * — `COMP_WORDS`/`COMP_CWORD` are read directly instead of via `_init_completion`.
 */

import type { CommandMeta } from './types';

function shellQuote(text: string): string {
  return `'${text.replace(/'/g, "'\\''")}'`;
}

function flagChoiceCase(flagName: string, spec: NonNullable<CommandMeta['specs']>[string], unitsVarRef: string): string | null {
  if (spec.type === 'boolean') return null;
  if (flagName === 'unit') return `        --unit) COMPREPLY=( $(compgen -W "${unitsVarRef}" -- "$cur") ); return ;;`;
  if (spec.choices && spec.choices.length > 0) {
    return `        --${flagName}) COMPREPLY=( $(compgen -W "${spec.choices.join(' ')}" -- "$cur") ); return ;;`;
  }
  return null;
}

function commandCaseBlock(command: CommandMeta, unitsVarRef: string): string {
  if (!command.specs) {
    // A bespoke command with no defineCli() call — nothing to complete beyond --help.
    return [
      `    ${command.name})`,
      '      COMPREPLY=( $(compgen -W "--help" -- "$cur") )',
      '      ;;',
    ].join('\n');
  }

  const flagNames = ['--help', ...Object.keys(command.specs).map((f) => `--${f}`)].join(' ');
  const choiceCases = Object.entries(command.specs)
    .map(([flagName, spec]) => flagChoiceCase(flagName, spec, unitsVarRef))
    .filter((line): line is string => line !== null);

  return [
    `    ${command.name})`,
    '      case "$prev" in',
    ...choiceCases,
    '      esac',
    `      COMPREPLY=( $(compgen -W "${flagNames}" -- "$cur") )`,
    '      ;;',
  ].join('\n');
}

export function generateBashCompletion(commands: CommandMeta[], opts: { units: string[] }): string {
  const commandNames = commands.map((c) => c.name).join(' ');
  const cases = commands.map((c) => commandCaseBlock(c, '$units')).join('\n');
  const units = opts.units.join(' ');

  return `# Generated by \`pipeline completion bash\`. Commands and flags are read live from
# apps/pipeline/src/commands/*.ts; PDF-derived --unit values are read live from apps/pipeline/content/pdf. Re-run
# \`source <(pipeline completion bash)\` (or open a new shell) after adding commands, flags, or PDFs.

_pipeline_complete() {
  local cur prev words cword
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  local units=${shellQuote(units)}

  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W ${shellQuote(commandNames + ' completion')} -- "$cur") )
    return
  fi

  local command="\${COMP_WORDS[1]}"
  case "$command" in
    completion)
      COMPREPLY=( $(compgen -W "zsh bash" -- "$cur") )
      ;;
${cases}
  esac
}

complete -F _pipeline_complete pipeline
`;
}
